# Generated by Django 5.0.2 on 2024-04-24 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_product_status'),
        ('production_plant', '0002_alter_productionplant_status'),
        ('unit', '0002_alter_unit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('batch_no', models.CharField(max_length=255, unique=True)),
                ('expected_delivery_date', models.DateTimeField(auto_now=True, null=True)),
                ('delivered_at', models.DateTimeField()),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('meta_data', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_created_by', to=settings.AUTH_USER_MODEL)),
                ('production_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proudction_plant', to='production_plant.productionplant')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'productions',
            },
        ),
        migrations.CreateModel(
            name='ProductionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='product.product')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_items', to='production.production')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_info', to='unit.unit')),
            ],
            options={
                'db_table': 'production_items',
            },
        ),
    ]
