# Generated by Django 5.0.2 on 2024-04-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='batch_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
