# Generated by Django 5.0.2 on 2024-04-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_production_batch_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='delivered_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
