# Generated by Django 5.0.2 on 2024-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_production_delivered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
