# Generated by Django 5.0.2 on 2024-05-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_productionitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionitem',
            name='quantity',
            field=models.IntegerField(max_length=8),
        ),
    ]
