# Generated by Django 5.0.2 on 2024-05-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_productionitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
