# Generated by Django 5.0.2 on 2024-04-28 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_order', '0002_alter_purchaseorder_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=255)),
                ('received_date', models.DateField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('meta_data', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quarantine', 'Quarantine'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_order_created_by', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_order_purchase_order', to='purchase_order.purchaseorder')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_order_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'received_orders',
            },
        ),
        migrations.CreateModel(
            name='ReceivedOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('storage_condition', models.CharField(choices=[('cold_storage', 'Cold Storage'), ('regular', 'Regular')], default='regular')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ro_purchase_order_item', to='purchase_order.purchaseorderitem')),
                ('received_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ro_received_order', to='received_order.receivedorder')),
            ],
            options={
                'db_table': 'received_order_items',
            },
        ),
    ]
