# Generated by Django 5.0.2 on 2024-04-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('received_order', '0002_alter_receivedorder_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedorder',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receivedorder',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
