# Generated by Django 5.0.2 on 2024-04-29 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('received_order', '0003_alter_receivedorder_meta_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedorderitem',
            name='received_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_order_items', to='received_order.receivedorder'),
        ),
    ]
