# Generated by Django 5.0.2 on 2024-05-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('received_order', '0004_alter_receivedorderitem_received_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedorderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
