# Generated by Django 5.0.2 on 2024-05-01 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.IntegerField(choices=[('material', 'Material'), ('order', 'Order')], default=0)),
                ('referance_id', models.CharField(max_length=50, unique=True)),
                ('return_to', models.CharField(blank=True, max_length=50, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[('pending', 'Pending'), ('returned', 'Returned')], default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'returns',
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('returns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='returns.returns')),
            ],
            options={
                'db_table': 'return_items',
            },
        ),
    ]
