# Generated by Django 5.0.2 on 2024-05-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='return_type',
            field=models.CharField(choices=[('material', 'Material'), ('order', 'Order')], default='material'),
        ),
        migrations.AlterField(
            model_name='returns',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('returned', 'Returned')], default='pending'),
        ),
    ]
