# Generated by Django 5.0.2 on 2024-03-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material_type', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('storage_type', models.CharField(choices=[('cold_storage', 'Cold_Storage'), ('regular', 'Regular')], default='regular', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_types', to='material_type.materialtype')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='unit.unit')),
            ],
            options={
                'db_table': 'materials',
            },
        ),
    ]
