# Generated by Django 5.0.2 on 2024-03-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('material_type', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_type', to='material_type.materialtype'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='unit.unit'),
        ),
    ]
