# Generated by Django 5.0.2 on 2024-04-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_material_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='storage_type',
            field=models.CharField(choices=[('cold_storage', 'Cold Storage'), ('regular', 'Regular')], default='regular', max_length=20),
        ),
    ]
