# Generated by Django 5.0.2 on 2024-04-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='metadata',
            field=models.JSONField(null=True),
        ),
    ]
