# Generated by Django 5.0.2 on 2024-04-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_warehouse_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
    ]
