# Generated by Django 5.0.2 on 2024-04-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='user_id',
            new_name='user',
        ),
    ]
