# Generated by Django 5.0.2 on 2024-04-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
