# Generated by Django 5.0.2 on 2024-04-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionplant',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
    ]
