# Generated by Django 5.0.2 on 2024-04-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='type',
            field=models.CharField(choices=[('common', 'Common'), ('raw', 'Raw'), ('finish', 'Finish')], default='raw'),
        ),
    ]
