# Generated by Django 5.0.2 on 2024-04-27 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0004_alter_department_status'),
        ('material', '0004_alter_material_storage_type'),
        ('production', '0002_alter_production_batch_no'),
        ('unit', '0002_alter_unit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date_requested', models.DateTimeField(auto_now=True, null=True)),
                ('expected_delivery_id', models.DateTimeField(auto_now=True, null=True)),
                ('delivered_at', models.DateTimeField(auto_now=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('purpose', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending')),
                ('meta_data', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_department', to='department.department')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_production', to='production.production')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requisitions',
            },
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_material_info', to='material.material')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_items', to='requisition.requisition')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_unit_info', to='unit.unit')),
            ],
            options={
                'db_table': 'requisition_items',
            },
        ),
    ]
