# Generated by Django 5.0.2 on 2024-04-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='expected_delivery_id',
        ),
        migrations.AddField(
            model_name='requisition',
            name='expected_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='date_requested',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
