# Generated by Django 5.0.2 on 2024-05-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0002_remove_requisition_expected_delivery_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
