# Generated by Django 5.0.2 on 2024-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0003_alter_requisitionitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
