# Generated by Django 5.0.2 on 2024-05-25 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0002_alter_unit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wastage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
                ('reference_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('batch_no', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('wastage_from', models.CharField(choices=[('storage', 'Storage'), ('production', 'Production'), ('finish_good', 'Finish Good')], default='production', max_length=20)),
                ('wastage_type', models.CharField(choices=[('actual', 'Actual'), ('overflow', 'Overflow')], default='regular', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wastage_approved_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastage_created_by', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastage_unit', to='unit.unit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wastage_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wastages',
            },
        ),
    ]
