# Generated by Django 5.0.2 on 2024-04-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtype',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0),
        ),
    ]
